<?php

namespace Database\Seeders;

use App\Models\Project;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class DefaultProjects extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $this->projects();
    }

    public function projects(){
        Project::truncate();
        $addresses = [
            [
                'country'   => 'United Kingdom',
                'zipcode'   => 'N1',
                'address'   => 'a:5:{s:7:"address";s:13:"London N1, UK";s:3:"lng";d:-0.08813879999999999;s:3:"lat";d:51.5412621;s:27:"administrative_area_level_1";a:2:{s:9:"long_name";s:7:"England";s:10:"short_name";s:7:"England";}s:7:"country";a:2:{s:9:"long_name";s:14:"United Kingdom";s:10:"short_name";s:2:"GB";}}',
            ],
            [
                'country'   => 'United Kingdom',
                'zipcode'   => 'N8',
                'address'   => 'a:5:{s:7:"address";s:13:"London N8, UK";s:3:"lng";d:-0.1236257;s:3:"lat";d:51.5833118;s:27:"administrative_area_level_1";a:2:{s:9:"long_name";s:7:"England";s:10:"short_name";s:7:"England";}s:7:"country";a:2:{s:9:"long_name";s:14:"United Kingdom";s:10:"short_name";s:2:"GB";}}',
            ],
            [
                'country'   => 'United Kingdom',
                'zipcode'   => 'N16',
                'address'   => 'a:5:{s:7:"address";s:14:"London N16, UK";s:3:"lng";d:-0.0764353;s:3:"lat";d:51.5623078;s:27:"administrative_area_level_1";a:2:{s:9:"long_name";s:7:"England";s:10:"short_name";s:7:"England";}s:7:"country";a:2:{s:9:"long_name";s:14:"United Kingdom";s:10:"short_name";s:2:"GB";}}',
            ],
            [
                'country'   => 'United Kingdom',
                'zipcode'   => 'NW5',
                'address'   => 'a:5:{s:7:"address";s:14:"London NW5, UK";s:3:"lng";d:-0.1441111;s:3:"lat";d:51.5543545;s:27:"administrative_area_level_1";a:2:{s:9:"long_name";s:7:"England";s:10:"short_name";s:7:"England";}s:7:"country";a:2:{s:9:"long_name";s:14:"United Kingdom";s:10:"short_name";s:2:"GB";}}',
            ],
            [
                'country'   => 'United Kingdom',
                'zipcode'   => 'NW6',
                'address'   => 'a:5:{s:7:"address";s:14:"London NW6, UK";s:3:"lng";d:-0.1970833;s:3:"lat";d:51.5437594;s:27:"administrative_area_level_1";a:2:{s:9:"long_name";s:7:"England";s:10:"short_name";s:7:"England";}s:7:"country";a:2:{s:9:"long_name";s:14:"United Kingdom";s:10:"short_name";s:2:"GB";}}',
            ],
            [
                'country'   => 'United Kingdom',
                'zipcode'   => 'W2',
                'address'   => 'a:5:{s:7:"address";s:13:"London W2, UK";s:3:"lng";d:-0.1703541;s:3:"lat";d:51.5096281;s:27:"administrative_area_level_1";a:2:{s:9:"long_name";s:7:"England";s:10:"short_name";s:7:"England";}s:7:"country";a:2:{s:9:"long_name";s:14:"United Kingdom";s:10:"short_name";s:2:"GB";}}',
            ],
            [
                'country'   => 'United Kingdom',
                'zipcode'   => 'W10',
                'address'   => 'a:5:{s:7:"address";s:14:"London W10, UK";s:3:"lng";d:-0.2146099;s:3:"lat";d:51.52269709999999;s:27:"administrative_area_level_1";a:2:{s:9:"long_name";s:7:"England";s:10:"short_name";s:7:"England";}s:7:"country";a:2:{s:9:"long_name";s:14:"United Kingdom";s:10:"short_name";s:2:"GB";}}',
            ],

        ];

        $description     = '<p>Nulla nisl sagittis, sed ulputate consequat pharetra. Leo mollis amet, duis elite musta nibhae quisque uate phaslus necerat scelerse. Sed turpis ullamcorper sed sit a vel pharetra porttitor odio non elit diam cursues Siet non, est curatur odion netus idsit enim consectur hendret mi, eget purus odio pellentes suspende. Sit nunc arcu vestibuum etarcu. Cursus fringilla commodo id aliquam commodo nisle suspendisse aemetneta auctor nonate volutpat ante est tempus enim ipsam voluptatem quiaptas sit aspernatur aut odit aute fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porero quisquam est, qui dolorem ipsum quia dolor sit amet consectetur, adipisci velit, sed quia non numquam eiustam eidi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.</p>';
        $description    .= '<p>Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid extmishea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esseam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur.</p>';
        $description    .= '<p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem antium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto.</p>';
        $description    .= '<ul><li>Cupiditate non provident, similique sunt in culpame magni dolores eos qui ratione</li><li>Quiofficia deserunt mollitia animi id est laborum etalorum voluptatem sequite</li><li>Et harum quidem rerum facilis expedita porero quisquam est, qui dolorem ipsum quia</li><li>Nam libero tempore cum soluta dolor sit amet consectetur adipisci velitem</li></ul>';
        $description    .= '<p>Nemo enim ipsam voluptatem quiaptas sit aspernatur aut odit aut fugit, sed quia consequuntur magniores eos qui ratione voluptatem sequi nesciunt. Neque porero quisquam est, qui dolorem ipsum quia doluor sit amet consectetur, adipisci velit, sed quia non numquam eiustam modi tempora incidunt ut labore etolore magnam aliquam quaerat voluptatem.</p>';
        $description    .= '<p>Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid extmishea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esseam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur.</p>';
        $description    .= '<p>Nemo enim ipsam voluptatem quiaptas sit aspernatur aut odit aut fugit, sed quia consequuntur magniores eos qui ratione voluptatem sequi nesciunt. Neque porero quisquam est, qui dolorem ipsum quia doluor sit amet consectetur, adipisci velit, sed quia non numquam eiustam modi tempora incidunt ut labore etolore magnam aliquam quaerat voluptatem.</p>';
        $description    .= '<p>Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid extmishea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esseam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur.</p>';

        $project_list = [
            [ // fixed project 1
                'author_id'	            => '2',
                'project_category'	    => '1',
                'project_title'	        => 'Sports and e-sports marketing scripting',
                'slug'	                => 'Sports and e-sports marketing scripting',
                'project_type'	        => 'fixed',
                'project_payout_type'   => 'fixed',
                'attachments'	        => 'a:1:{s:9:"video_url";s:43:"https://www.youtube.com/watch?v=XxxIEGzhIG8";}',
                'project_payment_mode'  => null,
                'project_max_hours'     => null,
                'project_min_price'     => '700',
                'project_max_price'     => '800',
                'project_duration'      => 3,
                'project_hiring_seller' => 3,
                'project_expert_level'  => 4,
                'project_location'      => 3,
                'is_featured'           => 1,
                'featured_expiry'       => null,
                'status'                => 'publish',
                'project_languages'     => [ 32, 33, 132, 140, 141, 142 ],
                'project_skills'        => [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14 ],
            ],
            [ // fixed project 2
                'author_id'	            => '3',
                'project_category'	    => '5',
                'project_title'	        => 'Test Applications Or Websites For Usability',
                'slug'	                => 'Test Applications Or Websites For Usability',
                'project_type'	        => 'fixed',
                'project_payout_type'   => 'fixed',
                'attachments'	        => 'a:1:{s:9:"video_url";s:43:"https://www.youtube.com/watch?v=XxxIEGzhIG8";}',
                'project_payment_mode'  => null,
                'project_max_hours'     => null,
                'project_min_price'     => '600',
                'project_max_price'     => '800',
                'project_duration'      => 3,
                'project_hiring_seller' => 4,
                'project_expert_level'  => 3,
                'project_location'      => 3,
                'is_featured'           => 0,
                'featured_expiry'       => null,
                'status'                => 'publish',
                'project_languages'     => [ 17, 20, 32, 41, 65, 136 ],
                'project_skills'        => [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14 ],
            ],
            [ // fixed project 3
                'author_id'	            => '4',
                'project_category'	    => '5',
                'project_title'	        => 'Convert PSD to HTML for WordPress theme',
                'slug'	                => 'Convert PSD to HTML for WordPress theme',
                'project_type'	        => 'fixed',
                'project_payout_type'   => 'fixed',
                'attachments'	        => 'a:1:{s:9:"video_url";s:43:"https://www.youtube.com/watch?v=XxxIEGzhIG8";}',
                'project_payment_mode'  => null,
                'project_max_hours'     => null,
                'project_min_price'     => '700',
                'project_max_price'     => '900',
                'project_duration'      => 2,
                'project_hiring_seller' => 4,
                'project_expert_level'  => 2,
                'project_location'      => 1,
                'is_featured'           => 1,
                'featured_expiry'       => null,
                'status'                => 'publish',
                'project_languages'     => [ 4, 17, 33, 39, 65],
                'project_skills'        => [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14 ],
            ],
            [ // fixed project 4
                'author_id'	            => '5',
                'project_category'	    => '5',
                'project_title'	        => 'Article And Do Content Writting',
                'slug'	                => 'Article And Do Content Writting',
                'project_type'	        => 'fixed',
                'project_payout_type'   => 'fixed',
                'attachments'	        => 'a:1:{s:9:"video_url";s:43:"https://www.youtube.com/watch?v=XxxIEGzhIG8";}',
                'project_payment_mode'  => null,
                'project_max_hours'     => null,
                'project_min_price'     => '600',
                'project_max_price'     => '700',
                'project_duration'      => 1,
                'project_hiring_seller' => 2,
                'project_expert_level'  => 3,
                'project_location'      => 1,
                'is_featured'           => 0,
                'featured_expiry'       => null,
                'status'                => 'publish',
                'project_languages'     => [ 4, 17, 33, 39, 65],
                'project_skills'        => [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14 ],
            ],
            [ // fixed project 5 
                'author_id'	            => '6',
                'project_category'	    => '7',
                'project_title'	        => 'Outbound long distance service',
                'slug'	                => 'Outbound long distance service',
                'project_type'	        => 'fixed',
                'project_payout_type'   => 'fixed',
                'attachments'	        => 'a:1:{s:9:"video_url";s:43:"https://www.youtube.com/watch?v=XxxIEGzhIG8";}',
                'project_payment_mode'  => null,
                'project_max_hours'     => null,
                'project_min_price'     => '650',
                'project_max_price'     => '700',
                'project_duration'      => 2,
                'project_hiring_seller' => 2,
                'project_expert_level'  => 4,
                'project_location'      => 2,
                'is_featured'           => 0,
                'featured_expiry'       => null,
                'status'                => 'publish',
                'project_languages'     => [ 4, 17, 33, 39, 65],
                'project_skills'        => [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14 ],
            ],
            [ // fixed both 6
                'author_id'	            => '5',
                'project_category'	    => '3',
                'project_title'	        => 'Managed network service',
                'slug'	                => 'Managed network service',
                'project_type'	        => 'fixed',
                'project_payout_type'   => 'both',
                'attachments'	        => 'a:1:{s:9:"video_url";s:43:"https://www.youtube.com/watch?v=XxxIEGzhIG8";}',
                'project_payment_mode'  => null,
                'project_max_hours'     => null,
                'project_min_price'     => '800',
                'project_max_price'     => '950',
                'project_duration'      => 3,
                'project_hiring_seller' => 4,
                'project_expert_level'  => 3,
                'project_location'      => 3,
                'is_featured'           => 0,
                'featured_expiry'       => null,
                'status'                => 'publish',
                'project_languages'     => [ 4, 17, 33, 39, 65],
                'project_skills'        => [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14 ],
            ],
            [ // fixed both 7 
                'author_id'	            => '4',
                'project_category'	    => '3',
                'project_title'	        => 'Customer premises equipment',
                'slug'	                => 'Customer premises equipment',
                'project_type'	        => 'fixed',
                'project_payout_type'   => 'both',
                'attachments'	        => 'a:1:{s:9:"video_url";s:43:"https://www.youtube.com/watch?v=XxxIEGzhIG8";}',
                'project_payment_mode'  => null,
                'project_max_hours'     => null,
                'project_min_price'     => '580',
                'project_max_price'     => '690',
                'project_duration'      => 1,
                'project_hiring_seller' => 3,
                'project_expert_level'  => 1,
                'project_location'      => 2,
                'is_featured'           => 0,
                'featured_expiry'       => null,
                'status'                => 'publish',
                'project_languages'     => [ 4, 17, 33, 39, 65],
                'project_skills'        => [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14 ],
            ],
            [ // fixed both 8
                'author_id'	            => '3',
                'project_category'	    => '5',
                'project_title'	        => 'Wavelength service',
                'slug'	                => 'Wavelength service',
                'project_type'	        => 'fixed',
                'project_payout_type'   => 'both',
                'attachments'	        => 'a:1:{s:9:"video_url";s:43:"https://www.youtube.com/watch?v=XxxIEGzhIG8";}',
                'project_payment_mode'  => null,
                'project_max_hours'     => null,
                'project_min_price'     => '890',
                'project_max_price'     => '998',
                'project_duration'      => 4,
                'project_hiring_seller' => 3,
                'project_expert_level'  => 2,
                'project_location'      => 2,
                'is_featured'           => 0,
                'featured_expiry'       => null,
                'status'                => 'publish',
                'project_languages'     => [ 4, 17, 33, 39, 65],
                'project_skills'        => [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14 ],
            ],
            [ // fixed milestone 9
                'author_id'	            => '2',
                'project_category'	    => '2',
                'project_title'	        => 'Generic services',
                'slug'	                => 'Generic services',
                'project_type'	        => 'fixed',
                'project_payout_type'   => 'milestone',
                'attachments'	        => 'a:1:{s:9:"video_url";s:43:"https://www.youtube.com/watch?v=XxxIEGzhIG8";}',
                'project_payment_mode'  => null,
                'project_max_hours'     => null,
                'project_min_price'     => '700',
                'project_max_price'     => '990',
                'project_duration'      => 3,
                'project_hiring_seller' => 3,
                'project_expert_level'  => 2,
                'project_location'      => 2,
                'is_featured'           => 0,
                'featured_expiry'       => null,
                'status'                => 'publish',
                'project_languages'     => [ 4, 17, 33, 39, 65],
                'project_skills'        => [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14 ],
            ],
            [ // fixed milestone 10 
                'author_id'	            => '3',
                'project_category'	    => '7',
                'project_title'	        => 'Direct inward dialing',
                'slug'	                => 'Direct inward dialing',
                'project_type'	        => 'fixed',
                'project_payout_type'   => 'milestone',
                'attachments'	        => 'a:1:{s:9:"video_url";s:43:"https://www.youtube.com/watch?v=XxxIEGzhIG8";}',
                'project_payment_mode'  => null,
                'project_max_hours'     => null,
                'project_min_price'     => '670',
                'project_max_price'     => '800',
                'project_duration'      => 3,
                'project_hiring_seller' => 2,
                'project_expert_level'  => 3,
                'project_location'      => 1,
                'is_featured'           => 1,
                'featured_expiry'       => null,
                'status'                => 'publish',
                'project_languages'     => [ 4, 17, 33, 39, 65],
                'project_skills'        => [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14 ],
            ],
            [ // fixed milestone 11
                'author_id'	            => '4',
                'project_category'	    => '7',
                'project_title'	        => 'Automation To Drop Shipping For Website',
                'slug'	                => 'Automation To Drop Shipping For Website',
                'project_type'	        => 'fixed',
                'project_payout_type'   => 'milestone',
                'attachments'	        => 'a:1:{s:9:"video_url";s:43:"https://www.youtube.com/watch?v=XxxIEGzhIG8";}',
                'project_payment_mode'  => null,
                'project_max_hours'     => null,
                'project_min_price'     => '670',
                'project_max_price'     => '800',
                'project_duration'      => 3,
                'project_hiring_seller' => 2,
                'project_expert_level'  => 3,
                'project_location'      => 3,
                'is_featured'           => 0,
                'featured_expiry'       => null,
                'status'                => 'publish',
                'project_languages'     => [ 4, 17, 33, 39, 65],
                'project_skills'        => [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14 ],
            ],
            [ // fixed milestone 12
                'author_id'	            => '5',
                'project_category'	    => '17',
                'project_title'	        => 'Add and upgrade plugin, Secure WordPress Website',
                'slug'	                => 'Add and upgrade plugin, Secure WordPress Website',
                'project_type'	        => 'fixed',
                'project_payout_type'   => 'milestone',
                'attachments'	        => 'a:1:{s:9:"video_url";s:43:"https://www.youtube.com/watch?v=XxxIEGzhIG8";}',
                'project_payment_mode'  => null,
                'project_max_hours'     => null,
                'project_min_price'     => '570',
                'project_max_price'     => '950',
                'project_duration'      => 3,
                'project_hiring_seller' => 2,
                'project_expert_level'  => 2,
                'project_location'      => 2,
                'is_featured'           => 0,
                'featured_expiry'       => null,
                'status'                => 'publish',
                'project_languages'     => [ 4, 17, 33, 39, 65],
                'project_skills'        => [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14 ],
            ],
            [ // hourly 13
                'author_id'	            => '6',
                'project_category'	    => '6',
                'project_title'	        => 'Wireless internet service provider Internet connections',
                'slug'	                => 'Wireless internet service provider Internet connections',
                'project_type'	        => 'hourly',
                'project_payout_type'   => 'hourly',
                'attachments'	        => 'a:1:{s:9:"video_url";s:43:"https://www.youtube.com/watch?v=XxxIEGzhIG8";}',
                'project_payment_mode'  => 'weekly',
                'project_max_hours'     => '39',
                'project_min_price'     => '40',
                'project_max_price'     => '59',
                'project_duration'      => 5,
                'project_hiring_seller' => 4,
                'project_expert_level'  => 1,
                'project_location'      => 1,
                'is_featured'           => 0,
                'featured_expiry'       => null,
                'status'                => 'publish',
                'project_languages'     => [ 4, 17, 33, 39, 65],
                'project_skills'        => [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14 ],
            ],
            [ // hourly 14
                'author_id'	            => '4',
                'project_category'	    => '5',
                'project_title'	        => 'Migration coding facility',
                'slug'	                => 'Migration coding facility',
                'project_type'	        => 'hourly',
                'project_payout_type'   => 'hourly',
                'attachments'	        => 'a:1:{s:9:"video_url";s:43:"https://www.youtube.com/watch?v=XxxIEGzhIG8";}',
                'project_payment_mode'  => 'daily',
                'project_max_hours'     => '5',
                'project_min_price'     => '40',
                'project_max_price'     => '70',
                'project_duration'      => 3,
                'project_hiring_seller' => 3,
                'project_expert_level'  => 3,
                'project_location'      => 3,
                'is_featured'           => 1,
                'featured_expiry'       => null,
                'status'                => 'publish',
                'project_languages'     => [ 4, 17, 33, 39, 65],
                'project_skills'        => [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14 ],
            ],
            [ // hourly 15
                'author_id'	            => '3',
                'project_category'	    => '7',
                'project_title'	        => 'WordPress website pages with digital marketing',
                'slug'	                => 'WordPress website pages with digital marketing',
                'project_type'	        => 'hourly',
                'project_payout_type'   => 'hourly',
                'attachments'	        => 'a:1:{s:9:"video_url";s:43:"https://www.youtube.com/watch?v=XxxIEGzhIG8";}',
                'project_payment_mode'  => 'monthly',
                'project_max_hours'     => '80',
                'project_min_price'     => '20',
                'project_max_price'     => '49',
                'project_duration'      => 4,
                'project_hiring_seller' => 2,
                'project_expert_level'  => 4,
                'project_location'      => 1,
                'is_featured'           => 0,
                'featured_expiry'       => null,
                'status'                => 'publish',
                'project_languages'     => [ 4, 17, 33, 39, 65],
                'project_skills'        => [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14 ],
            ],

        ];

        $addrass = [
            'country' => null,
            'zipcode' => null,
            'address' => null,
        ];
        foreach($project_list as $project){
            
            if($project['project_location'] == 3 ){
                $addrass = $addresses[rand(0,6)];
            }
            
            $createdProject = Project::create([
                'author_id'	            => $project['author_id'],
                'project_category'	    => $project['project_category'],
                'project_title'	        => $project['project_title'],
                'slug'	                => $project['slug'],
                'project_type'	        => $project['project_type'],
                'project_payout_type'   => $project['project_payout_type'],
                'attachments'	        => $project['attachments'],
                'project_description'   => json_encode($description),
                'project_payment_mode'  => $project['project_payment_mode'],
                'project_max_hours'     => $project['project_max_hours'],
                'project_min_price'     => $project['project_min_price'],
                'project_max_price'     => $project['project_max_price'],
                'project_country'       => $addrass['country'],
                'country_zipcode'       => $addrass['zipcode'],
                'address'               => $addrass['address'],
                'project_duration'      => $project['project_duration'],
                'project_hiring_seller' => $project['project_hiring_seller'],
                'project_expert_level'  => $project['project_expert_level'],
                'project_location'      => $project['project_location'],
                'is_featured'           => $project['is_featured'],
                'featured_expiry'       => $project['featured_expiry'],
                'status'                => $project['status'],
            ]);

            $createdProject->languages()->select('id')->sync($project['project_languages']);
            $createdProject->skills()->select('id')->sync($project['project_skills']);
        }

    }
}
